FROM node:10.12.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

RUN ["npm", "run", "build"]

RUN ["npm", "install", "-g", "serve"]

EXPOSE 3000

CMD [ "serve", "build", "-l", "3000" ]
