version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
  express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
