version: "3"

services:
  node:
    image: adrianmuchavazco/articles
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    deploy:
      replicas: 5
  express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
